Provide configuration option to run flake8 from project root.
dense-analysis/ale pull request #2858
Opened 2019-10-21 21:56 UTC by kalekseev

Option `per-file-ignores` was introduced in flake8 version 3.7.0.
It allows to ignore specific errors in specific files using glob syntax.
For example `per-file-ignores = src/generated/*.py:F401` will
ignore `F401` error in all python files in `src/generated`.
Thus ale have to run flake8 from project root where .flake8 config
is placed otherwise glob won't match linted file.

Not sure how that should be handled in ale style but I'm ready to follow on this pr.

2020-08-13 08:28 UTC, kalekseev commented
@w0rp please take a look, that feature can be useful

2020-08-28 07:10 UTC, w0rp requested changes

2020-08-28 07:10 UTC, w0rp commented on ale_linters/python/flake8.vim
> +    if l:change_directory == 2
We can do better than `2`. Let's add strings for the existing options and new option, and also continue to support `1` and `0`. Make sure to update the documentation, including the documented type.

Let's make this new setting the new default, and make sure we fall back on setting the CWD to the directory the file is in, in the Vader tests.

2020-08-30 20:02 UTC, kalekseev commented
Hi @w0rp, I updated the pr with changes you requested.

> and make sure we fall back on setting the CWD to the directory the file is in, in the Vader tests.

that implicitly tested by unrelated tests, because project root is default now and by default tests run on a file that doesn't have project mark in the parent dirs. If you prefer to have an explicit test for that case let me know.

2020-08-31 08:01 UTC, w0rp approved these changes

2020-08-31 08:01 UTC, merged

2020-08-31 08:01 UTC, w0rp commented
Cheers! :beers:

2020-09-01 01:56 UTC, rafikdraoui commented
Thanks! I've been using something similar to what's in this PR for a while now. I'm happy to be able to simplify my vimrc and use the default ale linter again!

The fact that `per-file-ignores` doesn't handle paths properly is a bug that is being tracked by `flake8`: https://gitlab.com/pycqa/flake8/-/issues/517.