Make C/C++ project files configurable
dense-analysis/ale pull request #3165
Opened 2020-05-10 16:42 UTC by proxict

New global variable `g:ale_c_project_filenames` allows users to configure which files trigger a directory as a C/C++ project root.

2020-08-20 19:48 UTC, proxict commented
Can somebody review this please?

2020-08-29 15:54 UTC, w0rp requested changes
This is a good idea.

This doesn't address #2831 totally. I would like to see another PR for parsing `compile_flags.txt`, which should be similar to parsing `command` keys from `compile_commands.json`. We could make our lives easy by reading the lines of output and converting them into the same JSON Dictionaries we get from `compile_commands.json`. We should always prefer `compile_commands.json` over `compile_flags.txt`, because the quoting of arguments will be better if the `arguments` keys are used in output, say from [Bear](https://github.com/rizsotto/Bear).

2020-08-29 15:54 UTC, w0rp commented on autoload/ale/c.vim
> +        for l:project_filename in g:ale_c_project_filenames
The documentation says you can use `b:ale_c_project_filenames`, so make that true.

```suggestion
        for l:project_filename in ale#Var(a:buffer, 'c_project_filenames')
```

2020-08-29 15:54 UTC, w0rp commented on autoload/ale/c.vim
> +\   'CMakeLists.txt',
```suggestion
\   'CMakeLists.txt',
\   'compile_flags.txt',
```

Let's add this here too, and write the same in the documentation for the option, so we do a little bit better project detection by default. You may have to break the default over many lines if it's long. You can use the hidden characters `>` and `<` in documentation to write multi-line code blocks. Search with `/>` and you'll find an example somewhere in the documentation.

2020-11-12 21:22 UTC, closed without merging