Dhall fixer support
dense-analysis/ale pull request #3261
Opened 2020-08-02 15:55 UTC by toastal

TODO: tests

Should fix #2820, but there's room to also

2020-08-02 17:20 UTC, toastal commented
I could use a little assistance here.  I ran `./run-tests -v -q --linters-only` and just like the failed [CI job](https://travis-ci.com/github/dense-analysis/ale/jobs/367658156), I'm getting 

```
...
========================================

Check Python code

========================================

.....

----------------------------------------------------------------------

Ran 5 tests in 0.001s

OK

Something went wrong!

The command "./run-tests -v $OPTIONS" exited with 1.

Done. Your build exited with 1.
``` 
This output isn't very helpful as it all looks okay.

2020-09-14 03:21 UTC, toastal commented
@w0rp tests are now passing; awaiting review.

2020-09-20 17:25 UTC, w0rp requested changes

2020-09-20 17:25 UTC, w0rp commented on autoload/ale/fix/registry.vim
> -\   'dhall': {
Add an alias to `dhall-format` for this, so anyone who is currently using the fixer under this name can keep using it.

2020-10-19 11:37 UTC, toastal commented
Alias was created @w0rp

2020-11-04 16:37 UTC, ldesgoui commented
Been using this for a few days, works great, thanks a lot for taking the time to contribute

2020-12-13 12:01 UTC, ldesgoui commented
This PR isn't stale as it's ready

2021-01-20 12:05 UTC, hsanson approved these changes
Looks good and indeed more feature-full.

2021-01-20 12:06 UTC, merged