bibclean: update matchlist reges for bibclean > v2.11.4
dense-analysis/ale pull request #3367
Opened 2020-09-26 01:26 UTC by bratekarate

Fixes #3366 

Legacy message pattern is still supported, as distributions like debian still package bibclean v2.11.4 from 2015. The legacy support could be removed in the future.

2020-09-26 06:04 UTC, hsanson requested changes
Require fixing the indentation and additional tests for the new bibclean format. Check `test_bibclean_handler.vader` file for example test.

2020-09-26 15:27 UTC, bratekarate commented
Applied the requested changes. I thought I ran the tests before, but that was a PR to another project, sorry.

Added another test case for bibclean > v2.11.4. I also made the matchlist regex for the legacy version more explicit, so it does not break if a colon is included in the message. I used the same bibclean message I used for the newer versions, because I did not know a legacy message that includes colons on the top of my head.

2020-09-28 01:53 UTC, hsanson approved these changes

2020-09-28 01:53 UTC, merged

2020-09-28 01:53 UTC, hsanson commented
Thanks.