Add support for V: "v" (compiler) and "vfmt" fixer.
dense-analysis/ale pull request #3622
Opened 2021-03-09 00:20 UTC by fiatjaf

https://vlang.io/

Based my changes mostly on the `gobuild` and `gofmt` code.

I'm not sure how to proceed regarding filetype, but I think it's something to be handled externally to this plugin, right? My Vim by default recognizes the `v` extension as `verilog`, but I told it to set it to `v`, then ale works fine with this PR.

2021-03-19 14:18 UTC, fiatjaf commented
Hey, not trying to pressure or anything, just want to know if is there anything missing here or what is needed to merge. Thank you!

2021-03-25 07:02 UTC, hsanson requested changes

2021-03-25 07:02 UTC, hsanson commented on autoload/ale/linter.vim
> +\   'v': ['v'],
Consider "vlang" as file type.

2021-03-25 17:41 UTC, fiatjaf commented on ale_linters/v/v.vim
> +call ale#linter#Define('v', {
I'm following the guidelines of the language itself, which is called "v", not "vlang". In the same sense "go" is called "go", not "golang".

See here: https://github.com/vlang/v/wiki/FAQ

Do you think it's reasonable that a Vim plugin with a handful of users gets to choose what is the language going to be called and not the language creators themselves? If you answer yes I'll change it to "vlang" here, no problem.

2021-03-26 00:39 UTC, hsanson commented on ale_linters/v/v.vim
> +call ale#linter#Define('v', {
I do not use this language myself so my knowledge is limited. If the language authors say "v" is the official file type then we should honor it.

2021-03-26 00:40 UTC, hsanson commented
If the conflict in autoload/ale/fix/registry.vim is solved I can merge this.

2021-03-26 01:19 UTC, fiatjaf commented
It's fixed now.

2021-03-26 06:38 UTC, hsanson approved these changes
Looks good. Thanks.

2021-03-26 06:38 UTC, merged