ocaml: prepare for  filetype separation, drop ols support
dense-analysis/ale pull request #3732
Opened 2021-05-22 15:30 UTC by undu

The ocaml filetype is currently used for several, different file
formats. This causes problems as not all tools support all formats.
New filetypes are introduced to support this separation, this needs some
changes in ale that are fortunately backwards-compatible.

These change add ocamlinterface file support for ocp-indent, merlin,
ocamlformat and ocaml-lsp. For ocaml-lsp I took the liberty to
add all recognised language ids, even if they are not supported.

ols has been removed as the project has been abandoned since 2019,
users are better served by other tools.

2021-05-22 15:35 UTC, undu commented
appveyor failure is unrelated to the change:

```
git clone -q --depth=10 https://github.com/dense-analysis/ale.git C:\testplugin
fatal: unable to access 'https://github.com/dense-analysis/ale.git/': Could not resolve host: github.com
Command exited with code 128
```

2021-05-25 00:26 UTC, hsanson requested changes
Changes seem ok except for removing ols that is a potential breaking change. Currently there is no defined procedure to remove supported tools from ALE and I would refrain from doing so unless is first announced (somehow) to give users time to phase the tool out or request it not to be removed.

I recommend moving the changes to remove ols support to a separate PR with an associated issue to inform and start discussion on if is ok to remove it from ALE.

2021-05-25 09:42 UTC, undu commented
That makes sense, I'll remove the changes to remove ols.

2021-05-27 07:33 UTC, hsanson approved these changes
Thanks for the changes. Looks good to me.

2021-05-27 07:33 UTC, merged