Added an explicit stdin argument to ansible-lint >=5.0.0
dense-analysis/ale pull request #3786
Opened 2021-06-27 23:09 UTC by jamescherti

Ansible-lint version >=5.0.0 ignores stdin when "-" or "/dev/stdin" is not explicitly specified:
```
:ALEInfo
(finished - exit code 0) ['/bin/bash', '-c', ''ansible-lint'' --parseable-severity -x yaml < ''/tmp/vVyvn4B/7/test2.yml'']
<<<NO OUTPUT RETURNED>>>'
```

This commit adds an explicit stdin  argument "-" to ansible_lint.vim (ansible-lint version >=5.0.0).

Tested with: ansible-lint 5.0.12 using ansible 2.11.2

**Steps to reproduce the bug:**

Create the file "test.yml":
```
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Shell test"
      shell: "ls /"
```

Execute "ansible-lint" without an explicit stdin argument:
```shell
ansible-lint --parseable-severity -x yaml < test.yml
```

Execute "ansible-lint" with an explicit stdin argument (it is working):
```shell
$ ansible-lint --parseable-severity --nocolor -x yaml - < test.yml
WARNING  Listing 1 violation(s) that are fatal
stdin:1: [internal-error] [VERY_HIGH] Unexpected error code 1 from execution of: ansible-playbook --syntax-check /tmp/tmp939mrvbkplaybook.yml
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - internal-error  # Unexpected internal error

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

2021-06-29 06:43 UTC, maxwell-k submitted a review, later dismissed

2021-07-04 11:27 UTC, hsanson requested changes
Tests need to be updated too.

2021-07-04 22:45 UTC, jamescherti commented
@hsanson @maxwell-k I have updated the tests.

2021-07-05 12:48 UTC, hsanson approved these changes
Thanks for the changes.

2021-07-05 12:48 UTC, merged