Add support for local PHPStan executables
dense-analysis/ale pull request #3809
Opened 2021-07-08 21:28 UTC by weeman1337

Usually you have PHPStan installed in your project. The location is `./vendor/bin/phpstan`.

This PR extends the PHPStan linter to pick up the project local executable if available.

2021-07-09 23:36 UTC, hsanson approved these changes
Thanks.

2021-07-09 23:37 UTC, hsanson requested changes
Some tests seem to be failing.

2021-07-10 10:43 UTC, weeman1337 commented
> Some tests seem to be failing.

There have been other changes yesterday. I will do a rebase and clean that up.

2021-07-10 13:56 UTC, hsanson approved these changes
Thanks.

2021-07-10 13:56 UTC, merged