Add support for jsonnetfmt and jsonnet-lint
dense-analysis/ale pull request #3907
Opened 2021-09-17 22:56 UTC by trevorwhitney

This adds support for linting jsonnet files with `jsonnet-lint` and `jsonnetfmt` as well as fixing them with `jsonnetfmt`. This was picked up from an out of date PR #3122. I did my best to add tests based on what I saw for other linters and fixers, not sure if more thorough testing is required? If so please point me to some examples and I'll do my best to extend testing.

2021-09-18 00:23 UTC, hsanson requested changes

2021-09-18 00:23 UTC, hsanson commented on ale_linters/jsonnet/jsonnet_lint.vim
> +    \   . (!empty(l:options) ? ' ' . l:options : '')
You can replace this with:

```
ale#Pad(l:options)
```

Look at the help `:h ale#Pad` for details.

2021-09-18 00:23 UTC, hsanson commented on ale_linters/jsonnet/jsonnetfmt.vim
> +    \   . (!empty(l:options) ? ' ' . l:options : '')
Same as with the linter you can use ale#Pad()  for this.

2021-09-18 00:23 UTC, hsanson commented on autoload/ale/fixers/jsonnetfmt.vim
> +    \       . (empty(l:options) ? '' : ' ' . l:options)
ale#Pad()

2021-09-18 00:23 UTC, hsanson commented on test/fixers/test_jsonnetfmt_fixer_callback.vader
> +  AssertEqual
Instead of AssertEqual we can use the dedicated AssertFixer. Check the help `:h ale-development-fixer-tests` for details on how to test fixers.

2021-09-20 20:24 UTC, trevorwhitney commented
@hsanson thanks for the review, changes made!

2021-09-21 01:49 UTC, hsanson approved these changes
Thanks, look good.

2021-09-21 01:49 UTC, merged