Implement virtual text support for vim
dense-analysis/ale pull request #3915
Opened 2021-09-23 00:11 UTC by vimpostor

This implements virtual text support for vim 8.2. It requires the text property and the popup feature.
<img width="515" alt="Screenshot_20210923_020429" src="https://user-images.githubusercontent.com/21310755/134438095-0ecf1455-3242-4d3f-9b95-e8833dc1f4dd.png">

2021-09-30 02:26 UTC, hsanson requested changes
Looks good but tests fail on vint linter:

```
========================================
Running Vint to lint our code
========================================
Vint warnings/errors follow:

autoload/ale/virtualtext.vim:52:30: unexpected token: # (see vim-jp/vim-vimlparser)
```

I verified it does not break things in nvim but I do not have vim 8.2 to test. Appreciated if others that use vim 8.2 can check how this works for them.

2021-09-30 11:28 UTC, vimpostor commented
> Looks good but tests fail on vint linter:
> 
> ```
> ========================================
> Running Vint to lint our code
> ========================================
> Vint warnings/errors follow:
> 
> autoload/ale/virtualtext.vim:52:30: unexpected token: # (see vim-jp/vim-vimlparser)
> ```
> 

Well, the linter is wrong, see `:h literal-Dict`. However, I have changed the code now to not use literal-Dicts to silence the linter gods (Make every key an explicit string):

```diff
diff --git a/autoload/ale/virtualtext.vim b/autoload/ale/virtualtext.vim
index 3e5c342f..2cd3a14d 100644
--- a/autoload/ale/virtualtext.vim
+++ b/autoload/ale/virtualtext.vim
@@ -49,7 +49,7 @@ function! ale#virtualtext#Clear() abort
         call nvim_buf_clear_highlight(l:buffer, s:ns_id, 0, -1)
     else
         if s:last_popup != -1
-            call prop_remove(#{type: 'ale'})
+            call prop_remove({'type': 'ale'})
             call popup_close(s:last_popup)
             let s:last_popup = -1
         endif
@@ -69,17 +69,17 @@ function! ale#virtualtext#ShowMessage(message, hl_group) abort
         call nvim_buf_set_virtual_text(l:buffer, s:ns_id, l:line-1, [[l:prefix.a:message, a:hl_group]], {})
     else
         let l:left_pad = col('$')
-        call prop_add(l:line, l:left_pad, #{
-        \ type: 'ale',
+        call prop_add(l:line, l:left_pad, {
+        \ 'type': 'ale',
         \})
-        let s:last_popup = popup_create(l:prefix.a:message, #{
-        \ line: -1,
-        \ padding: [0, 0, 0, 1],
-        \ mask: [[1, 1, 1, 1]],
-        \ textprop: 'ale',
-        \ highlight: a:hl_group,
-        \ fixed: 1,
-        \ wrap: 0
+        let s:last_popup = popup_create(l:prefix.a:message, {
+        \ 'line': -1,
+        \ 'padding': [0, 0, 0, 1],
+        \ 'mask': [[1, 1, 1, 1]],
+        \ 'textprop': 'ale',
+        \ 'highlight': a:hl_group,
+        \ 'fixed': 1,
+        \ 'wrap': 0
         \})
     endif
 endfunction
```

2021-10-02 00:01 UTC, hsanson approved these changes

2021-10-02 00:02 UTC, merged

2022-08-07 23:39 UTC, blayz3r commented
looks like vim has a virtual text API now