Add flakehell python linter (#3295)
dense-analysis/ale pull request #3921
Opened 2021-09-30 01:45 UTC by a666

Adds flakehell.

For the moment it is just a blatant copy of the flake8 linter.

2021-09-30 05:30 UTC, a666 commented on ale_linters/python/flakehell.vim
> +        let l:exec_args = ' -m flakehell'
This seemed to make more sense that appending it in the options.

2021-09-30 10:14 UTC, hsanson requested changes
Impressive PR, thanks.  One test on windows is failing, once that is fixed it looks good to merge:

```
    ( 7/17) [EXECUTE] (X) ['flakehell', ['flakehell --version', 'flakehell lint --format=default --stdin-display-name %s -']] should be equal to ['C:\testplugin\test\test-files\python\with_virtualenv\env\Scripts\flakehell', ['C:\testplugin\test\test-files\python\with_virtualenv\env\Scripts\flakehell --version', 'C:\testplugin\test\test-files\python\with_virtualenv\env\Scripts\flakehell lint --format=default --stdin-display-name %s -']]
 ```

2021-09-30 17:12 UTC, a666 commented
Thanks.
I'm unsure about how to fix that test, it is on parity with the (non-failing) flake8 test:
```diff
-Execute(The flake8 callbacks should detect virtualenv directories):
+Execute(The flakehell callbacks should detect virtualenv directories):
   silent execute 'file ' . fnameescape(g:dir . '/../test-files/python/with_virtualenv/subdir/foo/bar.py')

   let b:executable = ale#path#Simplify(
-  \ g:dir . '/../test-files/python/with_virtualenv/env/' . b:bin_dir . '/flake8'
+  \ g:dir . '/../test-files/python/with_virtualenv/env/' . b:bin_dir . '/flakehell'
   \)

   AssertLinter b:executable, [
   \ ale#Escape(b:executable) . ' --version',
   \ ale#Escape(b:executable)
+  \   . ' lint'
   \   . ' --format=default'
   \   . ' --stdin-display-name %s -',
   \]
```
And I don't see anything in the code that's done any differently with respect to flake8.
Am I missing something?

2021-10-02 01:58 UTC, a666 commented
Final test now passes.

2021-10-02 07:37 UTC, hsanson approved these changes
Thanks for the contribution.

2021-10-02 07:37 UTC, merged