Add volar support for vue
dense-analysis/ale pull request #3992
Opened 2021-11-19 21:34 UTC by creativenull

Includes the support of volar as an LSP server, addresses issue #3991

2021-11-20 09:59 UTC, hsanson requested changes

2021-11-20 09:59 UTC, hsanson commented on test/test-files/volar/src/App.vue
> +<script setup>
The contents of this file are not needed to run the tests so this can be empty.  No need to to make ALE bigger than what it is already.

2021-11-20 09:59 UTC, hsanson commented on test/test-files/volar/src/main.js
> +import { createApp } from 'vue'
This file does not seem needed for the tests so can be removed.

2021-11-20 09:59 UTC, hsanson commented on test/test-files/volar/tsconfig.json
> +{
This file also does not seem necessary.

2021-11-20 09:59 UTC, hsanson commented on test/test-files/volar/vite.config.js
> +import { defineConfig } from 'vite'
This file also does not seem necessary.

2021-11-21 11:02 UTC, hsanson approved these changes
Thanks for the changes.

2021-11-21 11:02 UTC, merged

2023-02-16 11:20 UTC, KKKiraSong commented
Thanks for adding volar support for vue3.
But I have some diffculties.
My vue config for ale is:
![image](https://user-images.githubusercontent.com/7237865/219350172-6678c467-84f0-4c30-9872-37a49c1cbb64.png)
Then I install volar: npm i -g @volar/vue-language-server. And the version is 1.0.24.
But when I open a vue file, it doesn't work.
![image](https://user-images.githubusercontent.com/7237865/219350754-47f2c72c-8ee0-4728-8b76-d308044d259b.png)
I define 'activeTabs', but I use 'activeTab' in template tag. ALE cannot work.
I have installed ts in my project.
I cannot find the reason. Plz help me.
Thank u.

2023-02-17 11:57 UTC, hsanson commented
This kind of support questions are better submitted to the discussions... commenting in a closed issue makes it difficult to spot for people that may be able to help:  https://github.com/dense-analysis/ale/discussions

Also please include input of ALEInfo as part of the question. It may provide details on what may be the problem.

2023-02-20 01:14 UTC, KKKiraSong commented
> This kind of support questions are better submitted to the discussions... commenting in a closed issue makes it difficult to spot for people that may be able to help: https://github.com/dense-analysis/ale/discussions
> 
> Also please include input of ALEInfo as part of the question. It may provide details on what may be the problem.

ok. Thanks