Add auto-fixer for crystal
dense-analysis/ale pull request #4016
Opened 2021-12-19 02:46 UTC by grepsedawk

Where are the tests? Have you added tests? Have you updated the tests? Read the
comment above and the documentation referenced in it first. Write tests!

Seriously, read `:help ale-dev` and write tests.

2021-12-25 17:36 UTC, grepsedawk commented
I don't think this test failing is this PR's fault

2021-12-26 12:05 UTC, hsanson requested changes

2021-12-26 12:05 UTC, hsanson commented on test/fixers/test_crystal_format_fixer_callback.vader
> +  \   'command': ale#Escape('xxxinvalid') . ' format -',
This test fails with:

```
    (1/2) [EXECUTE] (X) {'command': 'xxxinvalid tool format -'} should be equal to {'command': 'xxxinvalid format -'}
```

Make sure the test matches exactly what the `ale#fixers#crystal#Fix()` function returns. Including white spaces..

2021-12-26 12:05 UTC, hsanson commented on test/fixers/test_crystal_format_fixer_callback.vader
> +  AssertEqual
This test is falling with:

```
 (2/2) [EXECUTE] (X) {'command': 'xxxinvalid tool format -list=true -'} should be equal to {'command': 'xxxinvalid -list=true -'}
```

Again make sure the test matches exactly the return value of `ale#fixers#crystal#Fix()`.

2021-12-26 12:05 UTC, hsanson commented on autoload/ale/fixers/crystal.vim
> +    \       . (empty(l:options) ? '' : ' ' . l:options)
This can be replaced with:

```
ale#Pad(l:options)
```

2021-12-27 19:13 UTC, grepsedawk commented
Sick, those changes worked.
Thank you, I was struggling to find the failing specs previously but I was able to spot them now.

2021-12-28 11:23 UTC, hsanson approved these changes
Thanks for the contrib.

2021-12-28 11:23 UTC, merged