Fix 4083 - do not remove completion items that have additional text e…
dense-analysis/ale pull request #4084
Opened 2022-02-18 08:12 UTC by hsanson

Do not remove completion items if they have additional text edits and auto-import is off. But still only apply the additional edits if auto-import is on.

Fixes #4083

2022-03-02 18:30 UTC, w0rp requested changes
We'll have to find some other way of handling this. ALE is assuming any completion result that has some additional text is something adding an import line. With this change we'll start seeing items appear in the completion menu that require imports without importing them.

Maybe we just need to document that you have to turn the option on to use completion for certain language servers.

2022-03-02 18:57 UTC, w0rp commented
One thing I considered for this is that we could just turn the auto import option on by default and document that you might not get results if it's off.

2022-03-02 18:59 UTC, w0rp commented
Another, more complex option is to look at what the text edit is and compare it with what we'll be doing if it's not there, so if there's a redundant text edit in the results we throw it away. I can imagine there are language servers that return it when they don't need to.

2022-03-04 08:13 UTC, hsanson commented
Bit unfortunate since Java and Kotlin language servers seem to include additional text edits on every completion item they return rendering auto-completion unusable without auto-import enabled. Not seeing any auto-complete entries on my Java projects but seeing them for python/ruby led me to assume this was a bug, hence the issue and attempted fix.

I vote to enable auto-import by default and warn users that disabling it may affect auto-completion. This on the basis that ALE should just work out of the box without configuration.

I submitted another PR that does the changes #4102

2022-03-04 08:13 UTC, closed without merging

2022-03-04 19:02 UTC, w0rp commented
Yeah, I figured as much. They are probably redundantly including the text when just the name of the completion item would be enough. As I say, one trick we could try when auto-import is off is comparing the changes for text edits against the changes you'd get from inserting the completion item, and if they are the same, we could include that item in the menu.