remove --vanilla option
dense-analysis/ale pull request #4089
Opened 2022-02-19 21:01 UTC by uzsolt

With "--vanilla" option the Rscript does not read ~/.Renviron. In my case this file stores R_LIBS_USER variable which points to a user-installed R libraries (not system-wide).
My styler package is installed to my home directoy - and I think many people use install.packages(...) to his home directory (not only the default .libPaths()).
See a Q&A here: https://stackoverflow.com/questions/37970555/controversy-of-r-libs-user-path

Where are the tests? Have you added tests? Have you updated the tests? Read the
comment above and the documentation referenced in it first. Write tests!

Seriously, read `:help ale-dev` and write tests.

2022-02-20 00:14 UTC, hsanson requested changes
Thanks for the change but the tests also need to be updated with the change to be able to merge.

2022-02-20 06:15 UTC, uzsolt commented
> Thanks for the change but the tests also need to be updated with the change to be able to merge.

I see one test failed. I don't understand:

> 
>  Starting Vader: C:\testplugin\test\fixers\test_styler_fixer_callback.vader
>     (1/1) [EXECUTE] The styler callback should include custom styler options
>     (1/1) [EXECUTE] (X) {'read_temporary_file': 1, 'command': 'Rscript -e "suppressPackageStartupMessages(library(styler));style_file(commandArgs(TRUE), transformers = a_custom_option)" %t'} should be equal to {'read_temporary_file': 1, 'command': 'Rscript --vanilla -e "suppressPackageStartupMessages(library(styler));style_file(commandArgs(TRUE), transformers = a_custom_option)" %t'}

Should update this file too?

2022-02-20 06:57 UTC, hsanson commented
Yes, this PR removes the --vanilla flag from the command so the test also must be updated to reflect that change. Remove the --vanilla flag from the test case inside the test_styler_fixer_callback.vader file.

2022-03-02 18:53 UTC, w0rp commented
I happened to notice that #3744 is related while I'm finally updating the changelog after a long time.

2022-03-03 20:25 UTC, uzsolt commented
> I happened to notice that #3744 is related while I'm finally updating the changelog after a long time.
Sorry, I forgot this issue. Should I do everything or do you this? (I don't use Github deeply)

2022-03-04 05:50 UTC, hsanson commented
@uzsolt  please continue working on this PR since it is related to #3744 but is not the same. The change in #3744 removes --vanilla option from the linter while this one removes it from the fixer.

I do not use RScript but I see in #3744 that "--vanilla" option was replaced with "--no-save --no-restore --no-site-file --no-init-file". For consistency maybe would be good idea to do the same in this PR?? not sure if those options apply when using RScript as a fixer.

2022-03-07 20:08 UTC, uzsolt commented
I'm thinking about it. My opinion: the `--no-environ` should remove (so the `--vanilla` isn't good solution). 
The `--no-save`: it's okay. We don't need save the lint session. The `--no-restore` is same, we don't need restore any previously session.
The `--no-site-file` and `--no-init-file`: I'm not an expert R-user but in my case these options isn't annoying while linting/fixing.

So: the `--no-save` and `--no-restore` should use (it's clear). The `--no-site-file` and `--no-init-file` options _probably_ aren't needed while linting/fixing.

2022-03-20 13:55 UTC, w0rp commented
Update the options so the fixer and linter match some sensible options and I'll have a look.

2022-03-30 09:29 UTC, uzsolt commented
Sorry, I don't use github's so I think I did something wrong, I create a new pull request (https://github.com/dense-analysis/ale/pull/4129). I hope these patches will merge into one but no :(

2022-06-04 01:34 UTC, closed without merging