rust-analyzer for non-Cargo projects
dense-analysis/ale pull request #4118
Opened 2022-03-18 22:54 UTC by skyfmmf

rust-analyzer can also be used in non-cargo projects. This requires a rust-project.json file in the project root (https://rust-analyzer.github.io/manual.html#non-cargo-based-projects).

Make the rust-analyzer linter search for a rust-project.json file if no Cargo.toml file could be found; document it; and add tests for it.

2022-03-20 13:53 UTC, w0rp requested changes
I left some comments on syntax where we require blank lines between blocks and statements. Have a look at the failing tests.

2022-03-20 13:53 UTC, w0rp commented on ale_linters/rust/analyzer.vim
> +    if !empty(l:cargo_file)
```suggestion

    if !empty(l:cargo_file)
```

2022-03-20 13:53 UTC, w0rp commented on ale_linters/rust/analyzer.vim
> +    if !empty(l:rust_project)
```suggestion

    if !empty(l:rust_project)
```

2022-03-22 04:08 UTC, hsanson approved these changes
Looks good, thanks.

2022-03-23 01:56 UTC, merged