Add deadnix linter
dense-analysis/ale pull request #4443
Opened 2023-02-03 11:46 UTC by apeschar

[deadnix](https://github.com/astro/deadnix) detects unused variables in Nix code.

<img width="415" alt="Screenshot 2023-02-03 at 13 46 21" src="https://user-images.githubusercontent.com/122977/216595640-1fb16de1-7b7b-437c-835a-a17e240f730d.png">

2023-02-03 11:51 UTC, w0rp requested changes

2023-02-03 11:51 UTC, w0rp commented on autoload/ale/handlers/deadnix.vim
> +            let l:file = json_decode(l:line)
Use our `ale#util#FuzzyJSONDecode` function. It tends to handle weird things about JSON in Vim pretty well. I'd give it a default that isn't a Dictionary and then use `if type(l:file) is v:t_dict`.

2023-02-03 11:51 UTC, w0rp commented on ale_linters/nix/deadnix.vim
> +    return '%e -o json' . ale#Pad(ale#Var(a:buffer, 'nix_deadnix_options')) . ale#Pad('-- %t')
```suggestion
    return '%e -o json' . ale#Pad(ale#Var(a:buffer, 'nix_deadnix_options')) . ' -- %t'
```

The right `ale#Pad` call will always result in this basic string.

2023-02-07 08:23 UTC, hsanson approved these changes
Looks ok to me. Thanks.

2023-03-07 01:30 UTC, w0rp approved these changes

2023-03-07 01:31 UTC, merged

2023-03-07 01:31 UTC, w0rp commented
Cheers! :beers: