Clarify markdownlint
dense-analysis/ale pull request #4628
Opened 2023-10-07 09:49 UTC by sisrfeng

related issue: https://github.com/dense-analysis/ale/issues/4627

2023-11-19 08:59 UTC, w0rp requested changes
Can you keep the `[]()` syntax for this while still fixing the hyperlinks? The custom ALE CI checks will demand this format.

2023-11-20 08:57 UTC, sisrfeng commented
What about now?

2023-12-10 11:12 UTC, w0rp approved these changes

2023-12-10 11:14 UTC, w0rp commented
Have a look at the CI results. You can run the checks locally. Check `:help ale-dev`. The Vim text documentation needs to match the Markdown documentation.

2025-02-01 01:19 UTC, closed without merging