fix(biome): find root when using biome.jsonc
dense-analysis/ale pull request #4774
Opened 2024-05-13 16:16 UTC by redbmk

Since biome supports either `biome.json` or `biome.jsonc` config files, we need to look for both when searching for the LSP project root. We can also look for a package.json or .git folder to use. This uses mostly the same logic as deno.

I added some documentation for the new option and explained the new logic. This is pretty much copied from the deno documentation (and code) with some minor tweaks. Probably could refactor to some shared code at some point, just not sure where to put it.

I also added a couple tests and made sure tests and linting pass locally.

This will have minor conflicts with #4763 and #4773 but I wanted to keep the commits fairly atomic and the conflicts will be quick to clean up.

2024-06-21 05:38 UTC, redbmk commented
Guessing adding `biome.jsonc` somehow broke the deno tests. Not really seeing why that is, but getting tests set up locally again to test out some theories.

2024-06-21 05:40 UTC, Spixmaster commented
The new commits still do not solve the issue for me. I get the errors

```
 LSP Error Messages: 

(Errors for biome) 
Failed to find project root, language server won't start.
```

I do not understand since when I run the command `biome check advertisement.ts --config-path ~/.config/biome/biome.json` it executes successfully.

vimcr:
```
" Basic (priority)
set t_Co=256

"" Needed for 'set termguicolors'
let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"

" Plugins (priority)
"" vim-airline
let g:airline_powerline_fonts = 1
let g:airline_theme = 'molokai'

"" vim-ale
let g:ale_fix_on_save = 1
let g:ale_fixers =
            \{
            \    '*': ['remove_trailing_lines', 'trim_whitespace'],
            \    'bib': ['bibclean', 'remove_trailing_lines', 'trim_whitespace'],
            \    'cpp': ['clang-format', 'remove_trailing_lines', 'trim_whitespace'],
            \    'cmake': ['cmakeformat', 'remove_trailing_lines', 'trim_whitespace'],
            \    'css': ['css-beautify', 'remove_trailing_lines', 'stylelint', 'trim_whitespace'],
            \    'desktop': ['remove_trailing_lines', 'trim_whitespace'],
            \    'html': ['remove_trailing_lines', 'tidy', 'trim_whitespace'],
            \    'java': ['clang-format', 'remove_trailing_lines', 'trim_whitespace'],
            \    'json': ['dprint', 'remove_trailing_lines', 'trim_whitespace'],
            \    'mail': ['remove_trailing_lines', 'trim_whitespace'],
            \    'make': ['remove_trailing_lines', 'trim_whitespace'],
            \    'markdown': ['dprint', 'remove_trailing_lines', 'trim_whitespace'],
            \    'PKGBUILD': ['remove_trailing_lines', 'shfmt', 'trim_whitespace'],
            \    'po': ['remove_trailing_lines', 'trim_whitespace'],
            \    'python': ['autoflake', 'autopep8', 'isort', 'remove_trailing_lines', 'ruff', 'trim_whitespace', 'yapf'],
            \    'sh': ['remove_trailing_lines', 'shfmt', 'trim_whitespace'],
            \    'systemd': ['remove_trailing_lines', 'trim_whitespace'],
            \    'tex': ['latexindent', 'remove_trailing_lines', 'trim_whitespace'],
            \    'text': ['remove_trailing_lines', 'trim_whitespace'],
            \    'toml': ['dprint', 'remove_trailing_lines', 'trim_whitespace'],
            \    'typescript': ['dprint', 'remove_trailing_lines', 'trim_whitespace'],
            \    'vim': ['remove_trailing_lines', 'trim_whitespace'],
            \    'xml': ['remove_trailing_lines', 'trim_whitespace', 'xmllint'],
            \    'yaml': ['remove_trailing_lines', 'trim_whitespace', 'yamlfmt'],
            \    'zsh': ['remove_trailing_lines', 'shfmt', 'trim_whitespace']
            \}
let g:ale_linter_aliases =
            \{
            \    'PKGBUILD': 'sh',
            \    'zsh': 'sh'
            \}
""" Language servers are handled by YouCompleteMe and thus not included here.
let g:ale_linters =
            \{
            \    'bib': ['bibclean'],
            \    'cpp': ['clangtidy'],
            \    'cmake': ['cmake_lint'],
            \    'css': ['stylelint'],
            \    'desktop': ['desktop_file_validate'],
            \    'gitcommit': ['gitlint'],
            \    'html': ['htmlhint', 'tidy'],
            \    'java': ['javac', 'pmd'],
            \    'json': ['jq'],
            \    'mail': [],
            \    'make': ['checkmake'],
            \    'markdown': ['markdownlint'],
            \    'PKGBUILD': ['shell', 'shellcheck'],
            \    'po': ['msgfmt'],
            \    'python': ['bandit', 'mypy', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pyright', 'ruff', 'vulture'],
            \    'sh': ['shell', 'shellcheck'],
            \    'systemd': ['systemd_analyze'],
            \    'tex': ['chktex', 'lacheck'],
            \    'text': [],
            \    'toml': [],
            \    'typescript': ['biome'],
            \    'vim': ['vint'],
            \    'xml': ['xmllint'],
            \    'yaml': ['yamllint'],
            \    'zsh': ['shell', 'shellcheck']
            \}
let g:ale_linters_explicit = 1
let g:ale_virtualtext_cursor = 0

""" c
let g:ale_c_clangformat_options = '--style file:' . $XDG_CONFIG_HOME . '/clang/clang-format.yaml'

""" cmake
let g:ale_cmake_cmake_lint_options = '-c=' . $XDG_CONFIG_HOME . '/cmake-lang/cmake-lang.yaml'
let g:ale_cmake_cmakeformat_options = '-c=' . $XDG_CONFIG_HOME . '/cmake-lang/cmake-lang.yaml'

""" cpp
let g:ale_cpp_clangtidy_extra_options = '--config-file=' . $XDG_CONFIG_HOME . '/clang/clang-tidy.yaml'

""" css
let g:ale_css_css_beautify_options = '--config ' . $XDG_CONFIG_HOME . '/js-beautify/css-beautify.json'
let g:ale_css_stylelint_options = '--cache --cache-location ' . $XDG_CACHE_HOME . '/stylelint/ --config ' . $XDG_CONFIG_HOME . '/stylelint/stylelintrc.yaml'

""" dprint
let g:ale_dprint_config = $XDG_CONFIG_HOME . '/dprint/dprint.json'

""" html
let g:ale_html_htmlhint_options = '-c ' . $XDG_CONFIG_HOME . '/htmlhint/htmlhintrc.yaml'
let g:ale_html_tidy_options = '-config ' . $XDG_CONFIG_HOME . '/tidy/tidyrc -q'

""" java
let g:ale_java_pmd_options = '--cache ' . $XDG_CACHE_HOME . '/pmd/cache -R ' . $XDG_CONFIG_HOME . '/pmd/rules.xml'

""" markdown
let g:ale_markdown_markdownlint_executable = 'markdownlint-cli2'
let g:ale_markdown_markdownlint_options = '--config ' . $XDG_CONFIG_HOME . '/markdownlint/.markdownlint.yaml'

""" python
let g:ale_python_mypy_options = '--strict'
let g:ale_python_pycodestyle_options = '--max-line-length 120'
let g:ale_python_pyright_config =
            \{
            \    'pyright':
            \    {
            \        'disableLanguageServices': v:true,
            \        'disableOrganizeImports': v:false
            \    },
            \    'python':
            \    {
            \        'analysis':
            \        {
            \            'autoImportCompletions': v:true,
            \            'autoSearchPaths': v:true,
            \            'diagnosticMode': 'openFilesOnly',
            \            'diagnosticSeverityOverrides': {},
            \            'extraPaths': [],
            \            'logLevel': 'Information',
            \            'stubPath': '',
            \            'typeCheckingMode': 'strict',
            \            'typeshedPaths': [],
            \            'useLibraryCodeForTypes': v:true
            \        },
            \        'pythonPath': 'python',
            \        'venvPath': ''
            \    }
            \}
let g:ale_python_vulture_options = '--min-confidence 100'

""" sh
let g:ale_sh_shellcheck_options = '-a -Calways -o all -P SCRIPTDIR -S style -x'
let g:ale_sh_shfmt_options = '-ci -fn -i 4 -sr'

""" tex
let g:ale_tex_chktex_options = '-I -n 44'

""" typescript
let g:ale_biome_options = '--config-path ' . $XDG_CONFIG_HOME . '/biome/biome.json'

""" yaml
let g:ale_yaml_yamlfmt_options = '-conf ' . $XDG_CONFIG_HOME . '/yamlfmt/yamlfmt.yaml'
let g:ale_yaml_yamllint_options = '-c ' . $XDG_CONFIG_HOME . '/yamllint/yamllint.yaml'

"" vim-code-minimap
let g:minimap_auto_start = 1
let g:minimap_git_colors = 1
let g:minimap_highlight_search = 1
let g:minimap_width = 25

"" vim-gruvbox-community
let g:gruvbox_italic = 1

"" vim-nerdtree
let g:NERDTreeShowHidden = 1

"" vim-youcompleteme
let g:ycm_enable_semantic_highlighting = 1
""" Clang, jdt.ls, Jedi and TSServer are supported natively and therefore not included here.
let g:ycm_language_server =
            \[
            \    {
            \        'cmdline': ['autotools-language-server'],
            \        'filetypes': ['automake', 'config', 'make'],
            \        'name': 'autotools'
            \    },
            \    {
            \        'cmdline': ['cmake-language-server', 'start'],
            \        'filetypes': ['cmake'],
            \        'name': 'cmake'
            \    },
            \    {
            \        'cmdline': ['vscode-css-language-server', '--stdio'],
            \        'filetypes': ['css'],
      [...]

2024-06-21 06:09 UTC, redbmk commented
@Spixmaster 

> Why does Ale try to start the language server?

This is generally faster for linting because it can see changes as you type. Otherwise ALE would have to continually poll the `check` command or run it on file save or something.

Could you please try adding this line to see if it fixes the LSP for you?:

> ```vimrc
> let g:ale_biome_lsp_project_root = $XDG_CONFIG_HOME . '/biome/biome.json'
> ```

I wonder if the fixer should also use the same logic unless you're explicitly adding `--config-path` already. But I guess the fixer would run in the correct `cwd` I think so likely biome is already doing something similar.

I actually have some changes locally I haven't pushed up yet that change how the options work. I was thinking that since the only option shared across all commands is `--config-path`, then having the same `options` be used for both fixers and linters wouldn't make much sense.

2024-06-21 14:23 UTC, Spixmaster commented
@redbmk This branch makes it work for me.

```
let g:ale_biome_lsp_project_root = $XDG_CONFIG_HOME . '/biome/biome.json'
```

was not even necessary for it. It does not even have to do anything with one of the searched files `biome.json`, `biome.jsonc`, `package.json` or `.git` as I renamed them. Maybe, the directory of the file is chosen then, hence `bufname(a:buffer)`. I am not sufficient enough in the understanding to know that.

However, this works now with no configuration needed for me. Thank you very much.

2024-06-21 14:25 UTC, Spixmaster commented
@hsanson For me, this one works.

2024-06-24 22:35 UTC, hsanson requested changes
LGTM but has some conflicts that need to be resolved before I can merge.

2024-06-24 22:43 UTC, redbmk commented
@hsanson Thanks! Just updated to fix the conflicts

2024-06-25 08:18 UTC, hsanson approved these changes
Thanks.

2024-06-25 08:18 UTC, merged