Add fixer for json: python's json.tool
dense-analysis/ale pull request #4847
Opened 2024-10-22 02:38 UTC by idbrii

Resolves #4314. 

Add a fixer that's built into python for json formatting. Include a couple arguments in docs to make these features more discoverable.

Uses stdin-based fixing so you don't need to save the file to fix.

Unlike most python commands (i.e., pyflakes), this one doesn't seem to include a standalone executable. I can't find any other ale modules that get a python path, so this fixer has its own variable:
```
call ale#Set('json_pytool_executable', 'python')
```

2025-02-08 16:44 UTC, idbrii commented
Please don't close this PR.

2025-02-11 23:42 UTC, idbrii commented
That should fix lint errors.

2025-02-16 01:14 UTC, hsanson requested changes

2025-02-16 01:14 UTC, hsanson commented on doc/ale-json.txt
> +pytool                                                        *ale-json-pytool*
I think you need to make sure this name matches the one in the ToC: `json.tool` or the linter tests won't pass.

2025-02-20 07:28 UTC, idbrii commented on doc/ale-json.txt
> +pytool                                                        *ale-json-pytool*
Ah, I forgot to add it to the toc!

2025-02-20 08:31 UTC, idbrii commented
Ah, finally figured out toc lint issue: the validation pattern doesn't handle `.` in the name. Used `pytool` instead of `json.tool` to resolve.

2025-02-24 02:30 UTC, hsanson approved these changes
Thanks for the contribution.

2025-02-24 02:30 UTC, merged