Add golangci-lint fixer
dense-analysis/ale pull request #4853
Opened 2024-11-03 12:26 UTC by sigmavirus24

Closes #4616

2024-11-26 11:31 UTC, hsanson requested changes
There is a failing test.

2024-11-26 11:31 UTC, hsanson commented on autoload/ale/fixers/golangci_lint.vim
> +    \   . ' run'
Leave an space after after run or the options will be concatenated directly to the run command itself:

```suggestion
    \   . ' run '
```

2024-11-26 11:31 UTC, hsanson commented on test/fixers/test_golangci_lint_fixer_callback.vader
> +  \     . ' --fix testfile.go',
You need to escape the testfile.go here or the test equal assert won't match.

2024-11-26 11:31 UTC, hsanson commented on test/fixers/test_golangci_lint_fixer_callback.vader
> +  \     . ' --fix testfile.go',
```
Starting Vader: /testplugin/test/fixers/test_golangci_lint_fixer_callback.vader
    (1/3) [EXECUTE] The golangci-lint callback should return the correct default values
    (2/3) [EXECUTE] The golangci-lint callback should include custom golangci-lint options
    (3/3) [EXECUTE] The golangci-lint callback should support per-file mode
    (3/3) [EXECUTE] (X) {'command': '''xxxinvalid'' run --fix ''testfile.go'''} should be equal to {'command': '''xxxinvalid'' run --fix testfile.go'}
  Success/Total: 2/3
```

2024-11-27 13:17 UTC, hsanson approved these changes
Thanks for the fixes.

2024-11-27 13:17 UTC, merged

2024-11-27 14:23 UTC, sigmavirus24 commented
Thanks for accepting this and helping work through it. This is my first vim plug-in contribution ever